story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('addParticipants/<str:pk>/', views.addParticipants, name='addParticipants'),
    path('deleteActivity/<str:pk>/', views.deleteActivity, name='deleteActivity'),
    path('deletePerson/<str:pk>/', views.deletePerson, name='deletePerson'),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.index, name='index'),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.registerUser, name='register'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
]

storyv2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story9.urls')),
    path('story8/', include('story8.urls')),
    path('story7/', include('story7.urls')),
    path('story6/', include('story6.urls')),
]

story6/models.py
from django.db import models

class Activities(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class People(models.Model):
    name = models.CharField(max_length=20)
    activities = models.ManyToManyField(Activities)

    def __str__(self):
        return self.name

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story6/forms.py
from django import forms
from . import models
from crispy_forms.helper import FormHelper

class ActivityForm(forms.ModelForm):
    class Meta:
        model = models.Activities
        fields = '__all__'

    name = forms.CharField(label='Activity Name', max_length=20, widget=forms.TextInput(attrs=
    {
        'type' : 'text',
        'placeholder': 'Activity Name',
        'required' : 'True',
    }))


class PeopleForm(forms.ModelForm):
    class Meta:
        model = models.People
        fields = '__all__'

    name = forms.CharField(label='', max_length=20, widget=forms.TextInput(attrs=
    {
        'type' : 'text',
        'placeholder' : 'Insert Name',
        'required' : 'True',
    }))

story9/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    username = forms.CharField(label="Username", max_length=150, widget=forms.TextInput(attrs=
    {
        'class' : 'form-control',
        'placeholder' : 'Username',
    }))

    email = forms.EmailField(label="email", max_length=150, widget=forms.TextInput(attrs=
    {
        'class' : 'form-control',
        'placeholder' : 'Email',
    }))

    password1 = forms.CharField(label="Password", max_length=150, widget=forms.PasswordInput(attrs=
    {
        'class' : 'form-control',
        'placeholder' : 'Password',
    }))

    password2 = forms.CharField(label="Confirm Password", max_length=150, widget=forms.PasswordInput(attrs=
    {
        'class' : 'form-control',
        'placeholder' : 'Confirm Password',
    }))

story6/views.py
from django.shortcuts import render, redirect
from story6.models import *
from story6.forms import *

def index(request):
    data = Activities.objects.all()
    form = PeopleForm()
    context = {
        "data" : data,
        "form" : form,
    }
    return render(request, 'story6/index.html', context)

def addParticipants(request, pk):
    peopleData = People.objects.all()
    activity = Activities.objects.get(id=pk)
    name = request.POST['name']
    if request.method == 'POST':
        person = People(name=name)
        for i in peopleData:
            if person.name == i.name:
                person = People.objects.get(id=i.id)
                person.activities.add(activity)
                return redirect('/story6')
        person.save()
        person.activities.add(activity)
    return redirect('/story6')
    

def add(request):
    form = ActivityForm(request.POST or None)
    if form.is_valid and request.method == 'POST':
        form.save()
        return redirect('/story6')
    context = {
        "form" : form,
    }
    return render(request, 'story6/add.html', context)

def deleteActivity(request, pk):
    activity = Activities.objects.get(id=pk)
    activity.delete()
    return redirect('/story6')

def deletePerson(request, pk):
    person = People.objects.get(id=pk)
    person.delete()
    return redirect('/story6')

story7/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'story7/index.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests

def index(request):
    return render(request, 'story8/index.html')

def search(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    data = requests.get(url)
    json = data.json()
    return JsonResponse(json)

story9/views.py
from django.shortcuts import render, redirect
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

def index(request):
    context = {}
    return render(request, 'story9/index.html', context)

def registerUser(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account was succesfully created')
            return redirect('/login')
        else:
            messages.error(request, 'Account creation was unsuccessful')
    context = {
        'form' : form
    }
    return render(request, 'story9/register.html', context)

def loginUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, 'Username or Password is incorrect')
    context = {}
    return render(request, 'story9/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('/')

story6/templates/story6/add.html
{% extends 'story6/base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container align-items-center">	
  <div class="row justify-content-center align-items-center">
    <h1>Add Activity</h1>
  </div>
  <div class="card text-center d-flex justify-content-center align-items-center p-3">
    <form method="POST" class="is-valid">
      {% csrf_token %}
      {{ form.name|as_crispy_field }}
      <button class="btn btn-primary" type="submit">Add</button>
    </form>
	</div>
</div>

{% endblock content %}

story6/templates/story6/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'story6/styles.css' %}">
        <link rel="stylesheet" href="{% static 'navbar.css' %}">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <title>Story 6 - M. Irfan Junaidi</title>
    </head>
    <body>
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}
        <script>$("#s6").addClass('active');</script>
    </body>
</html>

story6/templates/story6/index.html
{% extends 'story6/base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container">	
		<h1 class="mt-4 text-center">Activities   <a href="{% url 'story6:add' %}"><i class="material-icons align-middle" style="font-size: 1.75rem;">add_circle_outline</i></a></h1>
		<hr class="mt-0 mb-4">
		<div class="card-columns">
			{% for activity in data reversed %}
			<div class="card mx-2">
				<div class="card-body">
					<h2 class="card-title text-center mb-4">{{ activity.name }}</h2>
					<h5 class="ml-3">Participants:</h5>
					<ul class="mr-3 mb-4">
						{% for person in activity.people_set.all %}
						<li class="mb-2">
							<div class="float-left text-truncate" style="width: 65%"><h6 class="card-text" style="display: inline;">{{ person.name }}</h6></div>
								<a class="btn btn-danger btn-xs float-right" href="{% url 'story6:deletePerson' pk=person.id %}" style="display: inline"><i class="material-icons" style="font-size: 15px;">delete</i></a>
						</li>
						{% endfor %}
					</ul>
					<form action="{% url 'story6:addParticipants' pk=activity.id %}" method="POST" class="is-valid mt-3">
						{% csrf_token %}
						<div class="d-flex flex-row align-items-center justify-content-center">
							{{ form.name|as_crispy_field }}
							<button class="btn btn-success btn-sm mb-3 ml-2" type="submit">
								<i class="material-icons">person_add</i>
							</button>
						</div>
					</form>
						<a class="btn btn-danger btn-sm" href="{% url 'story6:deleteActivity' pk=activity.id %}">Delete Activity</a>
				</div>
			</div>
			{% endfor %}
		</div>
</div>
{% endblock content %}

story7/templates/story7/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<link rel="stylesheet" href="{% static 'story7/styles.css' %}">
        <link rel="stylesheet" href="{% static 'navbar.css' %}">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <title>Story 7 - M. Irfan Junaidi</title>
    </head>
    <body>
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}
        {% block scripts %}
        {% endblock scripts %}
        <script>$("#s7").addClass('active');</script>
    </body>
</html>

story7/templates/story7/index.html
{% extends 'story7/base.html' %}

{% block content %}
<div class="container">	
    <div class="row justify-content-center px-2">
        <div class="col-10 pt-2">
            <h1 class="mt-4 pt-2">Accordion</h1>
            <hr class="mt-0 mb-4" style="max-width: 500px;">
        </div>
        <div class="accordion">
            <div class="card a1">
                <div class="card-header">
                    <div class="card-title">Current Activities</div>
                    <div class="card-btn">
                        <a class="btn btn-sm btn-up"><span class="material-icons">arrow_circle_up</span></a>
                        <a class="btn btn-sm btn-dw"><span class="material-icons">arrow_circle_down</span></a>
                    </div>
                </div>
                <div id="c1" class="card-body">
                    <ul>
                        <li>Lab 3 SDA</li>
                        <li>Story 7 PPW</li>
                        <li>PR 3 StatProb</li>
                        <li>Pop Quiz MatDas 2</li>
                    </ul>
                </div>
            </div>
            <div class="card a2">
                <div class="card-header">
                    <div class="card-title">Experiences</div>
                    <div class="card-btn">
                        <a class="btn btn-sm btn-up"><span class="material-icons">arrow_circle_up</span></a>
                        <a class="btn btn-sm btn-dw"><span class="material-icons">arrow_circle_down</span></a>
                    </div>
                </div>
                <div id="c2" class="card-body">
                    <ul>
                        <li>Teaching Assistant of Programming Foundations 1</li>
                        <li>Game Development Junior Member of Ristek Fasilkom UI</li>
                        <li>Supervision Commission Staff of DPM Fasilkom UI</li>
                        <li>Front-end Web Developer Staff of BETIS Fasilkom UI</li>
                    </ul>
                </div>
            </div>
            <div class="card a3">
                <div class="card-header">
                    <div class="card-title">Achievements</div>
                    <div class="card-btn">
                        <a class="btn btn-sm btn-up"><span class="material-icons">arrow_circle_up</span></a>
                        <a class="btn btn-sm btn-dw"><span class="material-icons">arrow_circle_down</span></a>
                    </div>
                </div>
                <div id="c3" class="card-body">
                    <ul>
                        <li>Gold Medalist of World Young Inventors Exhibition 2018</li>
                    </ul>
                </div>
            </div>
            <div class="card a4">
                <div class="card-header">
                    <div class="card-title">Hobbies</div>
                    <div class="card-btn">
                        <a class="btn btn-sm btn-up"><span class="material-icons">arrow_circle_up</span></a>
                        <a class="btn btn-sm btn-dw"><span class="material-icons">arrow_circle_down</span></a>
                    </div>
                </div>
                <div id="c4" class="card-body">
                    <ul>
                        <li>Code</li>
                        <li>Game</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    $(document).ready(function(){
        $(".card-title").click(function(){
            var head = $(this).parent();
            if (head.hasClass('active')) {
                head.toggleClass('active');
            } else {
                $(".card-header").removeClass('active');
                head.toggleClass('active');
            }
        });

        $(".btn-up, .btn-dw").click(function(){
            var block = $(this).parent().parent().parent()
            if ($(this).is(".btn-up")) {
                if (block.not(':first-child')) {
                    block.prev().before(block);
                } 
            } else {
                if (block.not(':last-child')) {
                    block.next().after(block);
                }
            }           
        });
    });
</script>
{% endblock scripts %}

story8/templates/story8/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<link rel="stylesheet" href="{% static 'story8/styles.css' %}">
        <link rel="stylesheet" href="{% static 'navbar.css' %}">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <title>Story 8 - M. Irfan Junaidi</title>
    </head>
    <body>
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}
        {% block scripts %}
        {% endblock scripts %}
        <script>$("#s8").addClass('active');</script>
    </body>
</html>

story8/templates/story8/index.html
{% extends 'story8/base.html' %}

{% block content %}
<div class="container">	
    <div class="row justify-content-center px-2">
        <div class="col-10 pt-2">
            <h1 class="mt-4 pt-2">Find Books</h1>
            <hr class="mt-0 mb-4">
        </div>
        <div class="col-10 input-group mb-3">
            <input type="text" id="search-box" class="form-control" placeholder="Books to find">
            <div class="input-group-append">
                <button class="btn btn-sm btn-outline-secondary" type="button" id="search-btn">
                    <span class="material-icons">search</span>
                </button>
            </div>
        </div>
    </div><br>
    <div class="row justify-content-center px-2">
        <div class="col-10 pt-2">
            <div class="card-columns" id="search-results"></div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    $(document).ready(function(){
        function search(){
            var search = $('#search-box').val();

            $.ajax({
                url : "{% url 'story8:search'%}" + "?q=" + search,
                success : function(data){
                    console.log(search);
                    $.each(data.items, function(i, book) {
                        if (!book.volumeInfo.imageLinks) var image = "https://i.imgur.com/6s7GIy9.png"
                        else var image = book.volumeInfo.imageLinks.thumbnail
                        $('#search-results').append(`
                        <div class="card">
                            <img class="card-img-top" style="max-height: 300px;" src="${image}" alt="Book">
                            <div class="card-body">
                                <h5 class="card-title">${book.volumeInfo.title}</h5>
                                <p>Author: ${book.volumeInfo.authors}</p>
                                <p>Publisher: ${book.volumeInfo.publisher}</p>
                            </div>
                        </div>`);
                    });
                },
                type : 'GET'
            });
        }

        $('#search-btn').click(function(){
            $('#search-results').empty();
            search();
        })
    });
    var input = $("#search-box");
    input.keypress("keyup", function(e) {
        if (e.keyCode === 13) {
            $("#search-btn").click();
        }
    });
</script>
    
{% endblock scripts %}

story9/templates/story9/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
		<link rel="stylesheet" href="{% static 'story9/styles.css' %}">
        <link rel="stylesheet" href="{% static 'navbar.css' %}">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        {% block title %}
        {% endblock title %}
    </head>
    <body>
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}
        {% block scripts %}
        {% endblock scripts %}
        <script>$("#home").addClass('active');</script>
    </body>
</html>

story9/templates/story9/index.html
{% extends 'story9/base.html' %}

{% block title %}
    <title>Home - Story PPW</title>
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center align-items-center px-2" id="homeC">
        <div class="col-10 pt-2">
            {% if request.user.username == '' %}
            <h1 class="mt-4 pt-2">Welcome, Traveler</h1>
            {% else %}
            <h1 class="mt-4 pt-2">Welcome, {{ request.user }}</h1>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
{% endblock scripts %}

story9/templates/story9/login.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
		<link rel="stylesheet" href="{% static 'story9/styles.css' %}">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <title>Login - Story PPW</title>
    </head>
    <body>
        <div class="container h-100">
            {% for message in messages %}
            {% if message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible fade show" style="position: absolute; width: 75vw; left: 12.5%; top: 15px;">
                <button type="button" class="close" data-dismiss="alert">×</button>
                {{ message }}
            </div>
            {% else %}
            <div class="alert alert-success alert-dismissible fade show" style="position: absolute; width: 75vw; left: 12.5%; top: 15px;">
                <button type="button" class="close" data-dismiss="alert">×</button>
                {{ message }}
            </div>
            {% endif %}
            {% endfor %}
            <div class="d-flex justify-content-center h-100">
                <div class="user_card">
                    <div class="d-flex justify-content-center">
                        <h2 id="form-title">Login</h2>
                    </div>
                    <div class="d-flex justify-content-center form_container">
                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="material-icons">person</i></span>
                                </div>
                                <input type="text" name="username" placeholder="Username" class="form-control">
                            </div>
                            <div class="input-group mb-2">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="material-icons">vpn_key</i></span>
                                </div>
                                <input type="password" name="password" placeholder="Password" class="form-control">
                            </div>
                               <div class="d-flex justify-content-center mt-3 login_container">
                                 <input class="btn login_btn" type="submit" value="Login">
                               </div>
                        </form>
                    </div>
            
                    <div class="mt-4">
                        <div class="d-flex justify-content-center links">
                            Don't have an account? <a href="{% url 'story9:register' %}" class="ml-1">Sign Up</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </body>
</html>

story9/templates/story9/register.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
		<link rel="stylesheet" href="{% static 'story9/styles.css' %}">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <title>Sign up - Story PPW</title>
    </head>
    <body>
        <div class="container h-100">
            {% for message in messages %}
            <div class="alert alert-danger alert-dismissible fade show">
                <button type="button" class="close" data-dismiss="alert">×</button>
                {{ message }}
            </div>
            {% endfor %}
            <div class="d-flex justify-content-center h-100">
                <div class="user_card">
                    <div class="d-flex justify-content-center">
                        <h2 id="form-title">Sign Up</h2>
                    </div>
                    <div class="d-flex justify-content-center form_container">
                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="input-group mb-2">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="material-icons">person</i></span>
                                </div>
                                {{ form.username }}
                            </div>
                            <p class="validation mb-1">{{ form.username.errors.as_text|cut:"* " }}</p>
                            <div class="input-group mb-2">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="material-icons">email</i></span>
                                </div>
                                {{ form.email }}
                            </div>
                            <p class="validation mb-1">{{ form.email.errors.as_text|cut:"* " }}</p>
                            <div class="input-group mb-2">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="material-icons">vpn_key</i></span>
                                </div>
                                {{ form.password1 }}
                            </div>
                            <p class="validation">{{ form.password1.errors.as_text|cut:"* " }}</p>
                            <div class="input-group mb-2">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="material-icons">vpn_key</i></span>
                                </div>
                                {{ form.password2 }}
                            </div>
                            {% for error in form.password2.errors %}
                            <p class="validation">{{ error }}</p>
                            {% endfor %}
                               <div class="d-flex justify-content-center mt-3 login_container">
                                 <input class="btn login_btn" type="submit" value="Sign Up">
                               </div>
                        </form>
                    </div>
            
                    <div class="mt-4">
                        <div class="d-flex justify-content-center links">
                            Already have an account? <a href="{% url 'story9:login' %}" class="ml-1">Login</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </body>
</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark sticky-top" id="navbar" style="background-color: rgb(56, 174, 220)">
    <a class="navbar-brand pl-5" href="/">irfancen</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <hr class="mt-0 mb-0 bg-light">
        <ul class="navbar-nav mt-2 mt-lg-0 ml-auto mr-5">
            <li class="nav-item">
                <a class="nav-link" id="home" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://irfancen-story.herokuapp.com/">Old Stories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="s6" href="/story6">Story 6</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="s7" href="/story7">Story 7</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="s8" href="/story8">Story 8</a>
            </li>
            {% if request.user.username == '' %}
            <li class="nav-item">
                <a class="nav-link" id="login" href="/login">Login</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" id="login" href="/logout">Logout</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% block content %}
{% endblock content %}
<script src="{% static 'navbar.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
<script>
    $('.navbar-nav .nav-link').click(function(){
    $('.navbar-nav .nav-link').removeClass('active');
    $(this).addClass('active');})
</script>